### ISSUE TITLE
add a mechanism to select specific images for language drivers

### ISSUE THREAD

**Issue by smola** [bblfsh/server#43]
Currently we always use `bblfsh/<lang>-driver:latest` but we should be able to select specific images for some languages with environment variables. That will be particularly useful for testing.

I would say something like `JAVA_DRIVER_IMAGE=myimage:foo` or `JAVA_DRIVER_IMAGE=docker-daemon:myimage:foo`, but this is open to discussion.

**Comment by abeaumont** [comment]
I think it'd be better to have a language agnostic solution, since we shouldn't make the server know about every language it'll support (and would be a PITA to maintain). So, I'd opt for a generic environment variable, something along:

`DRIVER_IMAGE="java=docker:myimage:foo;python=docker:anotherimage:bar"`

Opinions?

**Comment by smola** [comment]
@abeaumont sounds good
