### ISSUE TITLE
coala Collaboration

### ISSUE THREAD

**Issue by sils** [bblfsh/server#77]
Hi,

I was just made aware of this project and this sounds super interesting - first: I'm the founder of coala.io and we have been thinking about doing some universal AST as well but never got around doing it properly. It's great to see that there's an own project and effort around this concept!

coala is a python based open source code analysis *framework* with a dependency mechanism. The main idea here is that people can write a module that generates an AST (preferrably something like your UAST) and other modules that consume that one, coala handles parallelization, caching, user interaction etc.

Given that it'd be super cool if we could maybe collaborate on that to a degree. I see you already have a python client and I need to read up on this stuff but I could see us providing your UAST for researchers and programmers to write code analysis and maybe build a query language for the code analysis (maybe you already have something like this in mind).

I just read about this 5 mins ago and those are just a few initial thoughts, what do you think?

Cheers!

**Comment by sils** [comment]
CCing:

- @Udayan12167 @sims1253 from the coala research group
- @jayvdb because of being generally awesome and I presume interested in this stuff
- @fneu FYI

**Comment by mcuadros** [comment]
@sils I already knew coala.io, is an amazing project. 

The bblfsh project born with the idea of group the efforts from several companies and individual contributors, that's why it has his own organization and is not hosted at the company organization. Or why we have the [BIPs](https://doc.bblf.sh/proposals/), a formal way of suggest changes to the project.

We are very open on having external contributors in different levels:
- Contribute to the development of drivers
- Contribute to the development of the server and SDK
- Development of new tools on top of UAST as for example a code linter ;)

As @eiso wrote you by email we can have a call or chart in our the bblfsh [slack channel](http://sourced.tech/slackin).

**Comment by eiso** [comment]
@sils as @mcuadros mentioned, we'd love to collaborate! Babelfish and all of the work we contribute to at @src-d is designed to be an open source stack for ML & analysis on source code. 

Outside of having a call, definitely join the slack channel. The babelfish channel is where all discussions are happening and you see the latest work. I am excited to see what we can do together.

**Comment by sils** [comment]
[We feel right at home](https://github.com/coala/cEPs) :)

**Comment by sils** [comment]
Closing this issue to not clutter your tracker, we've started to bond and we'll see how everything goes. Seeing forward to this happening :)
